'use client';

import { ShareableCard as ShareableCardType } from '@/lib/types';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Share2, Copy, Download } from 'lucide-react';
import { formatTimestamp, copyToClipboard } from '@/lib/utils';

interface ShareableCardProps {
  card: ShareableCardType;
  onShare: (platform: string) => void;
}

export function ShareableCard({ card, onShare }: ShareableCardProps) {
  const handleCopyToClipboard = async () => {
    const success = await copyToClipboard(card.content);
    if (success) {
      alert('Content copied to clipboard!');
    } else {
      alert('Failed to copy content to clipboard');
    }
  };

  const downloadAsText = () => {
    const blob = new Blob([card.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bailiwick-${card.type}-${card.cardId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Card className="max-w-md mx-auto">
      <div className="text-center mb-4">
        <h3 className="text-lg font-semibold text-white capitalize">
          {card.type} Summary
        </h3>
        <p className="text-gray-400 text-sm">
          {formatTimestamp(card.timestamp)}
        </p>
      </div>
      
      <div className="bg-gray-800 rounded-lg p-4 mb-4">
        <pre className="text-white text-sm whitespace-pre-wrap font-mono">
          {card.content}
        </pre>
      </div>
      
      <div className="flex items-center justify-center space-x-2">
        <Button
          variant="secondary"
          size="sm"
          onClick={handleCopyToClipboard}
          className="flex items-center space-x-1"
        >
          <Copy className="w-4 h-4" />
          <span>Copy</span>
        </Button>
        
        <Button
          variant="secondary"
          size="sm"
          onClick={downloadAsText}
          className="flex items-center space-x-1"
        >
          <Download className="w-4 h-4" />
          <span>Download</span>
        </Button>
        
        <Button
          variant="primary"
          size="sm"
          onClick={() => onShare('sms')}
          className="flex items-center space-x-1"
        >
          <Share2 className="w-4 h-4" />
          <span>Share</span>
        </Button>
      </div>
      
      <div className="text-center mt-4">
        <p className="text-xs text-gray-400">
          Generated by Bailiwick Guides
        </p>
      </div>
    </Card>
  );
}
